[tool.black]
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.mypy_cache
    | omegaconf/grammar/gen
    | \.nox
    | build
    | vendor
  )
)
'''

[tool.pytest.ini_options]
addopts = "--import-mode=append -Werror -W 'ignore:pkg_resources is deprecated as an API:DeprecationWarning' -W 'ignore:Deprecated call to `pkg_resources:DeprecationWarning'"
pythonpath = ["."]

[tool.towncrier]
    package = "omegaconf"
    package_dir = ""
    filename = "NEWS.md"
    directory = "news/"
    title_format = "## {version} ({project_date})"
    template = "news/_template.rst"
    issue_format = "[#{issue}](https://github.com/omry/omegaconf/issues/{issue})"
    start_string = "<!-- TOWNCRIER -->\n"
    underlines = [""]

  [[tool.towncrier.type]]
  directory = "feature"
  name = "Features"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "bugfix"
  name = "Bug Fixes"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "api_change"
  name = "API changes and deprecations"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "docs"
  name = "Improved Documentation"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "misc"
  name = "Miscellaneous changes"
  showcontent = true
